# Generated by Django 4.0.2 on 2022-02-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default_g5kghd.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
