# Generated by Django 3.2.9 on 2022-01-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_customer', '0002_auto_20220112_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Input size of product', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
