# Generated by Django 3.2.9 on 2022-01-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_customer', '0002_auto_20220113_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
