# Generated by Django 3.2.9 on 2022-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_customer', '0005_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
